import { useState, type FormEvent } from "react";
import { Search, Loader2, AlertTriangle } from "lucide-react";
import { tokens, fonts } from "../lib/theme";
import { askQuestion, ApiError, type AnswerResponse } from "../lib/api";

const CONFIDENCE_STYLES = {
  high: { bg: tokens.amberSoft, border: tokens.moss, text: tokens.mossDeep, label: "High confidence" },
  medium: { bg: tokens.amberSoft, border: tokens.amber, text: "#7A5A1E", label: "Medium confidence" },
  low: { bg: "#FBEAEA", border: "#E3B4B4", text: "#8A2C2C", label: "Low confidence — verify before acting" },
};

// Display label per provider. Falls back to a capitalized raw string for
// any provider not listed here, so this never silently hides a value.
const PROVIDER_LABELS: Record<string, string> = {
  gemini: "Gemini",
  openai: "OpenAI",
  anthropic: "Claude",
  groq: "Groq",
};

function providerLabel(provider: string): string {
  return PROVIDER_LABELS[provider] ?? provider.charAt(0).toUpperCase() + provider.slice(1);
}

function CitationTag({ number, documentTitle, pageNumber }: { number: number; documentTitle: string; pageNumber: number | null }) {
  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 text-xs"
      style={{
        fontFamily: fonts.mono,
        background: tokens.amberSoft,
        color: "#7A5A1E",
        border: `1px solid ${tokens.amber}`,
      }}
    >
      [{number}] {documentTitle}
      {pageNumber != null ? `, p.${pageNumber}` : ""}
    </span>
  );
}

function ProviderBadge({ provider }: { provider: string }) {
  return (
    <span
      className="inline-flex items-center gap-1.5 text-xs px-2 py-1"
      style={{
        fontFamily: fonts.mono,
        background: tokens.surface,
        color: tokens.ink,
        border: `1px solid ${tokens.border}`,
      }}
      title={`This answer was generated by ${providerLabel(provider)}`}
    >
      <span
        aria-hidden
        style={{
          width: 6,
          height: 6,
          borderRadius: "50%",
          background: tokens.moss,
          display: "inline-block",
        }}
      />
      via {providerLabel(provider)}
    </span>
  );
}

function EscalationPrompt({ reason, contacts }: { reason: string | null; contacts: string[] }) {
  return (
    <div
      className="mt-4 p-4 flex gap-3"
      style={{ background: "#FFF7ED", border: "1px solid #F0C888" }}
      role="alert"
    >
      <AlertTriangle size={18} style={{ color: "#7A5A1E", flexShrink: 0, marginTop: 2 }} />
      <div>
        <p className="text-sm font-medium mb-1" style={{ color: "#7A5A1E" }}>
          This answer needs human review
        </p>
        {reason && (
          <p className="text-sm mb-2" style={{ color: tokens.inkSoft }}>
            {reason}
          </p>
        )}
        {contacts.length > 0 && (
          <p className="text-xs" style={{ fontFamily: fonts.mono, color: tokens.muted }}>
            Suggested contact{contacts.length > 1 ? "s" : ""}: {contacts.join(", ")}
          </p>
        )}
      </div>
    </div>
  );
}

export default function AskPanel() {
  const [question, setQuestion] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [answer, setAnswer] = useState<AnswerResponse | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!question.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const result = await askQuestion(question.trim());
      setAnswer(result);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Couldn't reach the server. Is the backend running?");
      setAnswer(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <form onSubmit={handleSubmit} className="flex gap-3">
        <input
          type="text"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          placeholder="e.g. What's the process for registering flood-affected households?"
          className="flex-1 px-3 py-2.5 text-base outline-none"
          style={{ background: tokens.surface, border: `1px solid ${tokens.border}`, color: tokens.ink }}
        />
        <button
          type="submit"
          disabled={loading || !question.trim()}
          className="cursor-pointer inline-flex items-center gap-2 px-5 py-2.5 text-sm shrink-0 disabled:opacity-60 disabled:cursor-not-allowed"
          style={{ background: tokens.moss, color: "#fff" }}
        >
          {loading ? <Loader2 size={16} className="animate-spin" /> : <Search size={16} />}
          Ask
        </button>
      </form>

      {error && (
        <div
          className="mt-4 text-sm px-3 py-2.5"
          style={{ background: "#FBEAEA", border: "1px solid #E3B4B4", color: "#8A2C2C" }}
          role="alert"
        >
          {error}
        </div>
      )}

      {answer && !error && (
        <div className="mt-6 p-6" style={{ background: tokens.surface, border: `1px solid ${tokens.border}` }}>
          <p className="text-base leading-relaxed mb-4" style={{ color: tokens.ink }}>
            {answer.answer}
          </p>

          <div className="flex flex-wrap items-center gap-2 mb-3">
            {answer.citations.map((c) => (
              <CitationTag key={c.number} number={c.number} documentTitle={c.document_title} pageNumber={c.page_number} />
            ))}
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <span
              className="inline-block text-xs px-2 py-1"
              style={{
                fontFamily: fonts.mono,
                background: CONFIDENCE_STYLES[answer.confidence].bg,
                color: CONFIDENCE_STYLES[answer.confidence].text,
                border: `1px solid ${CONFIDENCE_STYLES[answer.confidence].border}`,
              }}
            >
              {CONFIDENCE_STYLES[answer.confidence].label}
            </span>

            {answer.provider_used && <ProviderBadge provider={answer.provider_used} />}
          </div>

          {answer.needs_escalation && (
            <EscalationPrompt reason={answer.escalation_reason} contacts={answer.escalation_contacts} />
          )}
        </div>
      )}
    </div>
  );
}
