"""add document versioning fields

Revision ID: 5f4eae5e9282
Revises: 7923ae25a186
Create Date: 2026-07-25 17:46:05.887213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4eae5e9282'
down_revision: Union[str, None] = '7923ae25a186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('documents', sa.Column('supersedes_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('is_superseded', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'documents', 'documents', ['supersedes_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'is_superseded')
    op.drop_column('documents', 'supersedes_id')
    op.drop_column('documents', 'version')
    # ### end Alembic commands ###
