"""add chunk_index and chunked status

Revision ID: 773f186071c0
Revises: b857b0872ad3
Create Date: 2026-07-04 17:43:29.668044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773f186071c0'
down_revision: Union[str, None] = 'b857b0872ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'chunk_index')
    # ### end Alembic commands ###
