"""add access_level to documents

Revision ID: 97eaac7e4f4a
Revises: 0db5155d8117
Create Date: 2026-07-19 22:07:02.526771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97eaac7e4f4a'
down_revision: Union[str, None] = '0db5155d8117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('access_level', sa.String(length=20), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'access_level')
    # ### end Alembic commands ###
